version: '3.8'

volumes:
    prometheus_data: {}

networks:
  monitor-net:

services:

  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./PrometheusGrafana/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # expose:
    #   - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  pushgateway:
    image: prom/pushgateway
    # expose:
    #   - 9091
    ports:
      - "9091:9091"
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    networks:
      - monitor-net 

  script_exporter:
    image: ricoberger/script_exporter:v2.4.0
    volumes:
      - script_exporter/examples:bin/examples
    ports:
      - "9469:9469"
    # depoly:
    #   placement:
    #     constraints:
    #       - node.role==manager
    #   restart_policy:
    #     condition: on-failure
    # networks:
    #   - monitor-net

# docker run --network="host" --rm -it --name script_exporter -p 9469:9469 -v $(pwd)/examples:/examples ricoberger/script_exporter:dev -config.file /examples/config.yaml

# docker build -f ./Dockerfile -t ricoberger/script_exporter:dev .
